name: tadrib_hub
description: "A new Flutter project with advanced video player features."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  provider: ^6.1.5
  http: ^1.4.0
  dio: ^5.8.0+1
  shared_preferences: ^2.2.5
  url_launcher: ^6.3.0
  go_router: ^12.1.1
  equatable: ^2.0.5
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^8.1.0


  speech_to_text: ^7.0.0
  permission_handler: ^12.0.0+1
  image_picker: ^1.1.0
  file_picker: ^10.2.0
  path_provider: ^2.1.1

  image_gallery_saver_plus: ^4.0.1


  video_player: ^2.10.0
  video_player_android: ^2.4.10
  video_player_avfoundation: ^2.5.2


  google_generative_ai: ^0.2.0
  flutter_stripe: ^11.5.0


  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  webview_flutter: ^4.13.0

  fl_chart: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/

  # لو هتضيف خطوط مخصصة في المستقبل
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700
